// Generated by ReScript, PLEASE EDIT WITH CARE

import ReactCodemirror from "@uiw/react-codemirror";

async function main() {
  await import("@uiw/react-codemirror").then(function (m) {
        return m.default;
      });
}

export {
  main ,
}
/* @uiw/react-codemirror Not a pure module */
